apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
commonLabels:         
  argocd/app-name: c2q88fn1z-nodejs
  janus-idp.io/tekton: c2q88fn1z-nodejs
  backstage.io/kubernetes-id: c2q88fn1z-nodejs
  backstage.io/kubernetes-namespace: tssc-app 
  app.kubernetes.io/part-of: c2q88fn1z-nodejs
resources:
  - deployment.yaml
  - route.yaml
  - service.yaml
